---
defaultBaseImage: cgr.dev/chainguard/static

builds:
  - id: peribolos
    dir: .
    main: ./main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
