admins:
- auggie-bot
- cpanato
- justaugustus
billing_email: fake@example.com
company: ""
default_repository_permission: read
description: ""
email: ""
has_organization_projects: true
has_repository_projects: true
location: ""
members_can_create_repositories: true
name: ""
