admins:
- auggie-bot
- cpanato
- justaugustus
- sethmccombs
billing_email: foo@auggie.dev
company: ""
default_repository_permission: read
description: ""
email: ""
has_organization_projects: true
has_repository_projects: true
location: ""
members:
- detiber
members_can_create_repositories: true
name: ""
repos:
  ggreconcile:
    default_branch: main
    has_projects: true
  gh-jira-issue-sync:
    default_branch: main
    description: A tool for synchronizing issue tracking from GitHub to Jira
    has_projects: true
    homepage: https://pkg.go.dev/github.com/uwu-tools/gh-jira-issue-sync
  gh-sync-test:
    default_branch: main
    has_projects: true
  go-ghcrawl:
    default_branch: main
    has_projects: true
  issue-sync:
    allow_merge_commit: false
    allow_rebase_merge: false
    allow_squash_merge: false
    archived: true
    default_branch: main
    description: A tool for synchronizing issue tracking between GitHub and JIRA
    has_issues: false
    has_projects: true
    has_wiki: false
  k-release:
    description: Release infrastructure for Kubernetes and related components
    has_issues: false
    has_projects: true
    has_wiki: false
  peribolos:
    allow_merge_commit: false
    default_branch: main
    has_projects: true
    has_wiki: false
teams:
  gh-jira-issue-sync-admins:
    description: ""
    maintainers:
    - justaugustus
    members:
    - detiber
    privacy: closed
    repos:
      gh-jira-issue-sync: admin
  gh-jira-issue-sync-maintainers:
    description: ""
    maintainers:
    - justaugustus
    members:
    - detiber
    privacy: closed
    repos:
      gh-jira-issue-sync: maintain
  peribolos-admins:
    description: ""
    maintainers:
    - justaugustus
    - cpanato
    members:
    - detiber
    privacy: closed
    repos:
      peribolos: admin
  peribolos-maintainers:
    description: ""
    maintainers:
    - justaugustus
    - cpanato
    members:
    - detiber
    privacy: closed
    repos:
      peribolos: maintain
