admins:
- auggie-bot
- cpanato
- justaugustus
- sethmccombs
billing_email: foo@auggie.dev
company: ""
default_repository_permission: read
description: ""
email: ""
has_organization_projects: true
has_repository_projects: true
location: ""
members:
- detiber
members_can_create_repositories: true
name: ""
